### ISSUE TITLE
Secrets in your repo

### ISSUE THREAD

**Issue by smallbenji** [Mech654/MYzwitter#1]
Hey there @Mech654 

I have been looking through your projects, and have found a file with secrets inside of them. I do know that they are "only" for the SDE skp database server, but it's still a guess measure to not expose your secret keys inside Github repo's.

If you really need to have secrets inside your project, you could make the project private, and make a seperate repo to keep public for your portfolio without the secrets. Yes, it's a little more cluddered, but it's more secure.

https://github.com/Mech654/MYzwitter/blob/b5b9742a7b3334641d3227bd727c28bb3aa41013/Public/.env#L3

If you have questions, i will be happy to answer them for you 😄 

Happy coding

**Comment by Mech654** [comment]
Hey,
Looks like a oversee happened the file wasnt supposed to appear :/. It also not used anymore so i will get rid of it. Thanks for pointing that out😊
